version: "3.10"

networks:
  app-tier:
    driver: bridge


services:
  app:
    container_name: fastapi_app
    build: .
    command: uvicorn main:app --reload --host=0.0.0.0 --port=8000
    depends_on:
      - db
      - minio
    volumes:
      - ./app:/app/app
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=project_postgres
      - MINIO_SERVER_ACCESS_KEY=${access_key}
      - MINIO_SERVER_SECRET_KEY=${secret_key}
    env_file:
      - .env

  db:
    container_name: project_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always
    env_file:
      - .env

  minio:
    depends_on:
      - db
    container_name: project_minio
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioroot
      - MINIO_ROOT_PASSWORD=miniopassword
      - MINIO_DEFAULT_BUCKETS=test
    networks:
      - app-tier
    env_file:
      - .env