version: "3.10"

networks:
  app-tier:
    driver: bridge


services:
  app:
    container_name: fastapi_app
    build:
      context: .

    depends_on:
      - db
      - minio
#    command: sh -c 'while !/dev/tcp/postgres/5432; do sleep 1; done; uvicorn main:app --host 127.0.0.1 --port 8000'
    command: uvicorn main:app
    volumes:
      - ./app:/app/app
    ports:
      - 8000:8000
    restart: always
    environment:
      - MINIO_SERVER_ACCESS_KEY=${access_key}
      - MINIO_SERVER_SECRET_KEY=${secret_key}
    env_file:
      - .env
  db:
    container_name: project_postgres
    image: postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always
    env_file:
      - .env

  minio:
    depends_on:
      - db
    container_name: project_minio
    image: 'bitnami/minio:latest'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioroot
      - MINIO_ROOT_PASSWORD=miniopassword
    networks:
      - app-tier