
services:
  app:
    container_name: project_app
    build: ./
    depends_on:
      - db
    command: bash -c 'while !/dev/tcp/postgres/5432; do sleep 1; done; uvicorn app.main:app --host 127.0.0.1 --port 8000'
    volumes:
      - ./app:/app/app
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
  db:
    container_name: project_postgres
    image: postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always